### ISSUE TITLE
Undefined variable $wxt_active

### ISSUE THREAD

**Issue by duprasf** [drupalwxt/wxt_library#7]
When running the site, totally empty of content, using "Canada.ca (Government of Canada)" theme, the search form is giving this error:

> Warning: Undefined variable $wxt_active in Drupal\wxt_library\Form\SearchCanadaBlockForm->buildForm() (line 95 of modules/contrib/wxt_library/wxt_library/src/Form/SearchCanadaBlockForm.php).

**you need to add this code on line 94, I will try to do a pull request, my first, so I'm not sure what I'm doing**
```$wxt_active = $this->wxtLibraryServiceWxT->getLibraryName();```

**Comment by sylus** [comment]
Thanks for this we added this here:

https://github.com/drupalwxt/wxt_library/commit/fb865191bc8bb8fc8ea6c1a26b9aa7930e48dadf
