### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by sjpeters79** [drupalwxt/wxt_library#9]
Wxt Library makes a call to wxt_ext_layout_entity_get_display in:
- wxt_library/src/Plugin/Condition/PanelsTitle.php line 153

There's no dependency on wxt_ext_layout as such it throws an error:
`Error: Call to undefined function Drupal\wxt_library\Plugin\Condition\wxt_ext_layout_entity_get_display() in Drupal\wxt_library\Plugin\Condition\PanelsTitle->evaluate() (line 153 of /var/www/html/web/modules/contrib/wxt_library/src/Plugin/Condition/PanelsTitle.php).`

We basically have two options:

1.  Add dependency on wxt_ext_layout
2. Copy the function from wxt_ext_layout into PanelTitle condition plugin.

**Comment by sylus** [comment]
I made the fix by copying over the function :)
